### ISSUE TITLE
エンドポイント一覧

### ISSUE THREAD

**Issue by k-kbot** [k-kbot/praha-challenge-template#4]
## team
- [x] GET /teams
- [ ] PUT /teams/:id/pairs/:id
  - 所属するペアを変更できる

## pair
- [ ] GET /pairs
- [ ] PUT /pairs/:id/participants/:id
  - 所属する参加者を変更できる

## participant
- [ ] GET /participants
- [ ] POST /participants
- [ ] PUT /participants/:id
  - 在籍ステータスを更新できる
- [ ] DELETE /participants/:id

## task
- [ ] POST /tasks
- [ ] PUT /tasks/:id
  - 進捗ステータスを更新できる
- [ ] DELETE /tasks/:id
